name: Continuous Integration Pipeline

# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout repository
          uses: actions/checkout@v4
          with:
             fetch-depth: 0

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
             node-version: 20

        - name: Install dependencies and checkout main
          run: |
            BRANCH="${{ github.ref_name }}"
            git checkout $BRANCH
            npm install

        - name: Run Prettier Check
          run: |
            npm run format

        - name: Run Tests
          run: |
            npm run test